name: build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
      with:
        repository: microcai/gentoo-zh
        path: gentoo-zh
        fetch-depth: 5
    - name: packages
      id: packages
      run: |
        packages=$(git diff HEAD~ --name-only | xargs -I{} dirname {} | sort | uniq | grep -Ev '(\.|metadata|profiles)')
        echo "::set-output name=packages::$packages"
      working-directory: ${{github.workspace}}/gentoo-zh
    - name: docker
      run: |
        echo "${{ steps.packages.outputs.packages }}"

    #  uses: liangyongxiang/emerge-action@v0.1
    #  with:
    #    packages: dev-cpp/ETL
    #    overlay_name: gentoo-zh
    #    overlay_sync_type: git
    #    overlay_sync_uri: https://github.com/microcai/gentoo-zh.git
